source 'http://rubygems.org'

gem 'watirmark', :github => 'convio/watirmark'
gem 'watir-webdriver', :github => 'convio/watir-webdriver'
#gem 'watirmark_email', :github => 'convio/watirmark-email'

gem 'rake', '0.9.2.2'
gem 'cucumber', '~>1.2'
gem 'gherkin', '~>2.11'
gem 'multi_json'